apiVersion: v1
kind: Service
metadata: # Name of Service
  name: ping
spec:
  type: LoadBalancer # External service
  selector: # Define Pod to receive requests
    app: ping
  ports:
  - port: 80 # Request from
    targetPort: 9696 # Request to
